# Site
name: 'Pintereso'
description: 'Pintereso is a free Jekyll theme for awesome people like you, Pinterest like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/template-pintereso-bootstrap-jekyll'
avatar: 'assets/images/sal.jpg'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'

include:
  - "_pages"
  - "category"
  - "redirects"
permalink: /:title/

collections:
  pages:
    output: true
    permalink: /:path/
    
# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-archives

plugins:
  - jekyll-archives

# Cấu hình jekyll-archives để tạo trang danh mục
jekyll-archives:
  enabled:
    - categories
  layout: 'category-page'
  permalinks:
    category: '/category/:name/'
     
# Cấu hình jekyll-redirect-from để xử lý chuyển hướng
redirect_from:
  enabled: true


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
